/*
Chosen exercise:

Modify your solution to Lesson 1.14, Exercise 2 and introduce the sorts
`Decls`, `Decl`, and `Stmt` which include variable and function declaration
(without function parameters), and return and assignment statements, as well
as call expressions. Use `List` and `Map` to implement these operators, making
sure to consider the interactions between components, such as saving and
restoring the environment of variables at each call site. Don't worry about
local function definitions or global variables for now. Make sure to test the
resulting interpreter.
*/

module LESSON-16-SYNTAX
  
endmodule
